services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports: 
      - "9000:9000"
    depends_on: [backend]
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    ports:
      - "5252:5252"
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy
    ports: 
      - "80:80"